### ISSUE TITLE
优化建议

### ISSUE THREAD

**Issue by Openfan-Alex** [fanbook-wangdage/fb_bot_ws_examples#1]
可以删去代码中的代码高亮模块以及对封装的函数（还有判断收到消息的模块的使用的注释）写出较为详细的注释，来增强代码可读性与实用性 ，使不了解websocket的人也能快速上手fanBOT开发
- [ 跑路]

**Comment by wangdage12** [comment]
#2已解决

**Comment by Openfan-Alex** [comment]
> #2已解决



> #2已解决

哦，真是美妙
